### ISSUE TITLE
Is it deprecated?

### ISSUE THREAD

**Issue by kamituel** [matthiasn/systems-toolbox-ui#1]
Hey!
I saw in the [trailing mouse pointer example](https://github.com/matthiasn/systems-toolbox/tree/master/examples/trailing-mouse-pointer) that `systems-toolbox-ui` is pretty much no longer used, and you used re-frame instead. That's an approach I like a lot, to be honest (not wrapping Reagent components within systems-toolbox's components).

So I was wondering - did you give it some thought, and systems-toolbox-ui will become deprecated at some point? Or has it just been an experiment?

**Comment by matthiasn** [comment]
Hey Kamil, thanks for spotting this. Yes, I'm actually not using it at all any more in my latest projects, also not in the client project I mentioned recently. Using re-frame like in the example is indeed much more convenient. So yeah, let's call this deprecated. I already removed the library from BirdWatch recently and I'll remove it from the example with the counters as well.
